- name: Create AWS Creds File and Add Creds
  hosts: docker_servers
  become: yes
  become_user: root
  tasks:
  - name: Create aws folder
    file:
      path: /root/.aws
      state: directory
  - name: Create credentails file
    file:
      path: /root/.aws/credentials
      state: touch
  - name: Added Content
    lineinfile:
      path: /root/.aws/credentials
      line: "{{ item }}"
    with_items:
      - '[default]'
      - AWS_ACCESS_KEY_ID = AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    no_log: true
  #- name: Delete Folder
    #shell: rm -rf /root/.aws