---
  - name: Play for Install Nginx on WebServers
    hosts: webservers:appservers
    gather_facts: yes #yes or no
    become: yes
    become_user: root
    #serial: 1 #Executes the playbook one host at a time.
    pre_tasks:
    - name: Adding Delay for 15 seconds
      wait_for:
        timeout: 20
    tasks:
       - name: Run Apt Update
         shell: apt update
         tags:
           - update

       - name: Clone Git Repo
         shell: cd /tmp && git clone https://github.com/DevOps-Harsha/Ansible-Notes.git
         tags:
           - clone